version: 2
jobs:
  build:
    docker:
      - image: cimg/node:12.22
    steps:
      - checkout
    name: Install dependencies
      - run: npm install
    name: Lint (Eslint)
      - run: npm run lint:all
    name: Format (Prettier)
      - run: npm run format
    name: Tests
      - run:
          command: npm test
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
    name: Check TypeScript
      - run: npm run check-typescript
      - run:
          name: dependency audit
          command: ./scripts/better-audit.sh
      - store_test_results:
          path: reports/junit/
      - store_artifacts:
          path: reports/junit/
